### ISSUE TITLE
BUG,BLD: Fix / cleanup the CI

### ISSUE THREAD

**Issue by amritagos** [d-SEAMS/seams-core#16]
Currently the runs fail on valid PRs which is confusing.

**Comment by HaoZeke** [comment]
`nix` has linking issues for `fmt` and `yaml-cpp` it seems. So the CI needs to be cleaned though this error is mirrored locally. Currently the best approach seems to be `spack` though it is the longest. Otherwise, without `lua` the builds work fine with the `mamba` enviroment as well.
