### ISSUE TITLE
BUG: fmt version error in linux

### ISSUE THREAD

**Issue by RuhiRG** [d-SEAMS/seams-core#26]
**Describe the bug**
I was trying to work with d-seams in linux as it did not work with M1 macos. 

**To Reproduce**
I was trying to build d-seams using the following commands:

```bash
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_INSTALL_PREFIX:PATH=$CONDA_PREFIX ../
make -j$(nproc)
```

**Expected behavior**
It was supposed to work in linux, but it gave an error stating fmt==9 was undefined.

**Screenshots**

<img width="970" alt="Screenshot 2023-06-19 at 4 49 02 AM" src="https://github.com/d-SEAMS/seams-core/assets/108693964/ba83ac6a-28c9-4757-ad1a-2ce4e7a8d3f5">

**Desktop (please complete the following information):**

<img width="790" alt="Screenshot 2023-06-19 at 4 58 26 AM" src="https://github.com/d-SEAMS/seams-core/assets/108693964/05212e52-c54c-4af8-bc10-a805e26b9270">

**Additional context**
The problem here was my linux machine had fmt==10 version installed and the code didn't support fmt==10 version and is restricted to fmt==9.

**Comment by HaoZeke** [comment]
This might have something to do with needing `fmt::streamed()`..
